### ISSUE TITLE
Text Messaging Support

### ISSUE THREAD

**Issue by khurramengr** [duttaime/WebRTCAndroid#1]
Thank your @duttaime for this great demo.
I was wondering if it is possible to send text messages in the meeting?

**Comment by duttaiam** [comment]
You will need to create a new DataChannel for text messages. It should be pretty easy since the PeerConnection is already established. Refer this link for some code snippets -
http://myhexaville.com/2018/03/12/android-webrtc-datachannel-sending-text-messages/
