### ISSUE TITLE
How to share screen remotely in a video call?

### ISSUE THREAD

**Issue by vismay11** [duttaime/WebRTCAndroid#2]
What if someone wants to **share** their **screen** in an ongoing video call?
Sharing screen by going to SettingsActivity is fine but it's real use is when we can share our screen in an ongoing video call.

**Comment by duttaiam** [comment]
As you have pointed out screen sharing functionality exists but you will have to tweak the code to make it available in the call screen. This is just a demo project for webrtc android.
