### ISSUE TITLE
There is a problem with the docker image .

### ISSUE THREAD

**Issue by mmabluesky** [duttaime/WebRTCAndroid#3]
When I start the mirror server, the app connects to the server, and the WebSocketRTCClient file prompts  “json object erro”.

**Comment by duttaiam** [comment]
I tried the following steps on a smallest DigitalOcean droplet Ubuntu 16.04 (64 bit) and it worked perfectly fine.

apt-get update
apt-get upgrade
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
apt-get update
apt-cache policy docker-ce
apt-get install -y docker-ce
systemctl status docker

docker run --rm --net=host \
  -e PUBLIC_IP=xx.xxx.xx.xx \
  -it piasy/apprtc-server

Used http://xx.xxx.xx.xx:8080 as the room url.
