### ISSUE TITLE
Call get disconnected after few seconds

### ISSUE THREAD

**Issue by kumaillakhani** [duttaime/WebRTCAndroid#4]
Hello,
First of all Great work!
I am having an issue when I am making a call it gets disconnected after few seconds. Please guide me what is the issue?

**Comment by duttaiam** [comment]
You haven't provided enough information to debug. I assume you're connecting to the default sever i.e appr.tc. What messages do you see in Logcat before it disconnects. Do you have a stable network (wifi) connection? If so, try with your own server installation using the docker image (link provided in README).

**Comment by kumaillakhani** [comment]
Yes I am connecting to the default server i.e appr.tc.
Currently I am installing docker on my machine meanwhile could please tell me on which language your server code is written on? Can I view your server code without using docker?

I want to use your code in my project I have following questions:
1. Is their any documentation written for your code if I got stuck some where so I can refer your documentation?
2. have you used any framework in server code or in Android code?

**Comment by duttaiam** [comment]
You will find all information (links) in the README page itself. The source code comes from the WebRTC project.

**Comment by duttaiam** [comment]
Were you able to reproduce the issue on your own server installation? Otherwise, will close the issue.

**Comment by kumaillakhani** [comment]
Hi,
I am still trying to install docker on my windows machine its requires some update so I am updating my machine. please don't close this issue.

**Comment by kumaillakhani** [comment]
Hi,
I am not able to install docker on my machine because my windows is not updating. I have no idea of server side. I am trying your [mentioned server](https://github.com/duttaime/WebRTCAndroid) but I am not able to understand steps how I can set it up locally?

I have installed following things on my machine:
Google App Engine SDK for Python, Node.js and Grunt.

I ran command npm install
I am getting this:
> $ npm install
> 
> iltorb@1.3.10 install E:\KumailRaza\server\apprtc\node_modules\iltorb
> detect-libc prebuild-install || node-gyp rebuild
> 
> prebuild-install WARN install No prebuilt binaries found (target=10.15.3 runtime=node arch=x64 platform=win32)
> 
> E:\KumailRaza\server\apprtc\node_modules\iltorb>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
> gyp ERR! configure error
> gyp ERR! stack Error: Command failed: C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack   File "<string>", line 1
> gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack                                ^
> gyp ERR! stack SyntaxError: invalid syntax
> gyp ERR! stack
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
> gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
> gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> gyp ERR! System Windows_NT 6.3.9600
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd E:\KumailRaza\server\apprtc\node_modules\iltorb
> gyp ERR! node -v v10.15.3
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iltorb@1.3.10 (node_modules\iltorb):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iltorb@1.3.10 install: `detect-libc prebuild-install || node-gyp rebuild`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> 
> audited 5686 packages in 37.609s
> found 3 vulnerabilities (1 low, 2 high)
>   run `npm audit fix` to fix them, or `npm audit` for details`

npm audit fix doesn't solve this issue.

**Comment by duttaime** [comment]
Can you checkout the below repo and see if it solves your issue?
`https://github.com/eranpolo/WebRTCAndroid`

**Comment by duttaiam** [comment]
I have to merge a PR and i assume your connection issues are one off. So i am closing the issue for now and will look into it if reported by someone else.
